language: go

go:
  - 1.7
  - 1.8
  - tip

matrix:
    allow_failures:
        - go: tip

install:
  - mkdir -p $GOPATH/src/gopkg.in/src-d
  - mv $(pwd) $GOPATH/src/github.com/TroyWind/proteus
  - cd $GOPATH/src/github.com/TroyWind/proteus
  - go get -t -v ./...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
